const atmData = [
    {
        id: '45678901',
        shortName: 'Sample2a',
        atmStatus: 'Offline',
        amount: 800000,
        cashJam: '',
        cashStatus: '',
        cardReader: '',
        receiptPrinter: '',
        escalated: 'Yes'
    },
    {
        id: '45634001',
        shortName: 'Phoenix2a',
        atmStatus: '1',
        amount: 300000,
        cashJam: 'Jammed',
        cashStatus: 'Low Cash',
        cardReader: 'Ok',
        receiptPrinter: 'Faulty',
        escalated: 'Yes'
    },
    {
        id: '45211331',
        shortName: 'Hover3',
        atmStatus: '1',
        amount: 0,
        cashJam: 'Ok',
        cashStatus: 'Out of Cash',
        cardReader: 'Ok',
        receiptPrinter: 'Ok',
        escalated: 'Yes'
    },
    {
        id: '45211332',
        shortName: 'Ghost2a',
        atmStatus: '1',
        amount: 6000000,
        cashJam: 'Ok',
        cashStatus: 'Ok',
        cardReader: 'Ok',
        receiptPrinter: 'Ok',
        escalated: 'Yes'
    },
    {
        id: '45211333',
        shortName: 'Ghost4a',
        atmStatus: '1',
        amount: 100000,
        cashJam: 'Ok',
        cashStatus: 'Ok',
        cardReader: 'Ok',
        receiptPrinter: 'Ok',
        escalated: 'Yes'
    },
    {
        id: '45211337',
        shortName: 'Ghost7a',
        atmStatus: '1',
        amount: 10000,
        cashJam: 'Jammed',
        cashStatus: 'Low Cash',
        cardReader: 'Ok',
        receiptPrinter: 'Faulty',
        escalated: 'Yes'
    },
    {
        id: '45211339',
        shortName: 'Ghost8a',
        atmStatus: '1',
        amount: 200000,
        cashJam: 'Ok',
        cashStatus: 'Low Cash',
        cardReader: 'Ok',
        receiptPrinter: 'Faulty',
        escalated: 'Yes'
    },
    {
        id: '45223339',
        shortName: 'Jolt1b',
        atmStatus: '1',
        amount: 2000000,
        cashJam: 'Ok',
        cashStatus: 'Ok',
        cardReader: 'Faulty',
        receiptPrinter: 'Ok',
        escalated: 'Yes'
    },
    {
        id: '22212339',
        shortName: 'Jolt3b',
        atmStatus: '1',
        amount: 156000,
        cashJam: 'Jammed',
        cashStatus: 'Ok',
        cardReader: 'Ok',
        receiptPrinter: 'Faulty',
        escalated: 'Yes'
    },
    {
        id: '28932569',
        shortName: 'Jolt6b',
        atmStatus: 'Offline',
        amount: 0,
        cashJam: '',
        cashStatus: '',
        cardReader: '',
        receiptPrinter: '',
        escalated: 'Yes'
    },
    {
        id: '28967569',
        shortName: 'Jolt9b',
        atmStatus: '1',
        amount: 1000,
        cashJam: 'Ok',
        cashStatus: 'Low Cash',
        cardReader: 'Ok',
        receiptPrinter: 'Ok',
        escalated: 'Yes'
    },
    {
        id: '21737569',
        shortName: 'Penta0m',
        atmStatus: 'Offline',
        amount: 653000,
        cashJam: '',
        cashStatus: '',
        cardReader: '',
        receiptPrinter: '',
        escalated: 'Yes'
    },
    {
        id: '21791519',
        shortName: 'Penta2m',
        atmStatus: '1',
        amount: 591000,
        cashJam: 'Ok',
        cashStatus: 'Ok',
        cardReader: 'Ok',
        receiptPrinter: 'Ok',
        escalated: 'Yes'
    },
    {
        id: '21795519',
        shortName: 'Penta3m',
        atmStatus: '1',
        amount: 91000,
        cashJam: 'Ok',
        cashStatus: 'Ok',
        cardReader: 'Ok',
        receiptPrinter: 'Ok',
        escalated: 'Yes'
    },
    {
        id: '31795519',
        shortName: 'Agnostic8',
        atmStatus: '1',
        amount: 70000,
        cashJam: 'Jammed',
        cashStatus: 'Ok',
        cardReader: 'Ok',
        receiptPrinter: 'Ok',
        escalated: 'Yes'
    },
    {
        id: '31295519',
        shortName: 'Agnostic9',
        atmStatus: '1',
        amount: 1170000,
        cashJam: 'Ok',
        cashStatus: 'Ok',
        cardReader: 'Ok',
        receiptPrinter: 'Faulty',
        escalated: 'Yes'
    },
    {
        id: '31215319',
        shortName: 'Kont2',
        atmStatus: '1',
        amount: 9170000,
        cashJam: 'Jammed',
        cashStatus: 'Ok',
        cardReader: 'Ok',
        receiptPrinter: 'Faulty',
        escalated: 'Yes'
    },
    {
        id: '31316111',
        shortName: 'Kent9',
        atmStatus: '1',
        amount: 9100,
        cashJam: 'Ok',
        cashStatus: 'Low Cash',
        cardReader: 'Ok',
        receiptPrinter: 'Faulty',
        escalated: 'Yes'
    },
    {
        id: '00316111',
        shortName: 'Trump1',
        atmStatus: '1',
        amount: 1100,
        cashJam: 'Ok',
        cashStatus: 'Low Cash',
        cardReader: 'Ok',
        receiptPrinter: 'Faulty',
        escalated: 'Yes'
    },
    {
        id: '00420061',
        shortName: 'Trump2',
        atmStatus: '1',
        amount: 8500,
        cashJam: 'Ok',
        cashStatus: 'Low Cash',
        cardReader: 'Ok',
        receiptPrinter: 'Faulty',
        escalated: 'Yes'
    },
    {
        id: '00426161',
        shortName: 'Trump3',
        atmStatus: '1',
        amount: 6800,
        cashJam: 'Ok',
        cashStatus: 'Low Cash',
        cardReader: 'Ok',
        receiptPrinter: 'Ok',
        escalated: 'Yes'
    },
    {
        id: '00496060',
        shortName: 'Trump7',
        atmStatus: '1',
        amount: 3200,
        cashJam: 'Ok',
        cashStatus: 'Low Cash',
        cardReader: 'Ok',
        receiptPrinter: 'Ok',
        escalated: 'Yes'
    },
    {
        id: '00596060',
        shortName: 'Bob12',
        atmStatus: 'Offline',
        amount: 312200,
        cashJam: '',
        cashStatus: '',
        cardReader: '',
        receiptPrinter: '',
        escalated: 'Yes'
    },
    {
        id: '00601231',
        shortName: 'Olympus2a',
        atmStatus: '1',
        amount: 402200,
        cashJam: 'Ok',
        cashStatus: 'Ok',
        cardReader: 'Ok',
        receiptPrinter: 'Ok',
        escalated: 'Yes'
    },
    {
        id: '00890231',
        shortName: 'Olympus4a',
        atmStatus: '1',
        amount: 902200,
        cashJam: 'Ok',
        cashStatus: 'Ok',
        cardReader: 'Ok',
        receiptPrinter: 'Ok',
        escalated: 'Yes'
    },
    {
        id: '00892231',
        shortName: 'Olympus6a',
        atmStatus: '1',
        amount: 900000,
        cashJam: 'Ok',
        cashStatus: 'Ok',
        cardReader: 'Ok',
        receiptPrinter: 'Ok',
        escalated: 'Yes'
    },
    {
        id: '00821331',
        shortName: 'Olympus6a',
        atmStatus: 'Offline',
        amount: 0,
        cashJam: '',
        cashStatus: '',
        cardReader: '',
        receiptPrinter: '',
        escalated: 'Yes'
    },
]

export default atmData